preload = /home/sam/.config/kitty/backgrounds/background.png

wallpaper = DP-2,/home/sam/.cache/wallpaper-picker/wallpaper_DP-2.png
wallpaper = DP-3,/home/sam/.config/kitty/backgrounds/background.png

splash = false
